export const generalPersonalPrompts: Array<unknown> = [
	{
		id: '1683298282949357570',
		title: '欧洲 backpacking 旅行计划',
		promptCategoryId: '1683297786922577921',
		description: '规划一次历时两周的欧洲 backpacking 旅行',
		content:
			'我希望你能帮我规划一次历时两周的欧洲 backpacking 旅行。我想要参观以下几个城市：巴黎、阿姆斯特丹、柏林和罗马。我希望你能提供一份详细的行程，包括旅行的日期、交通方式、住宿地点以及每个城市的重点景点。',
		sortNo: 1,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683298394631090178',
		title: '预算有限的泰国游',
		promptCategoryId: '1683297786922577921',
		description: '在预算有限的情况下规划一次泰国旅行',
		content:
			'我希望你能帮我规划一次预算有限的泰国旅行，总预算为1000美元。我计划在泰国停留7天，其中包括到曼谷和清迈两个城市。我希望你能帮我找到便宜的住宿、美食和景点。',
		sortNo: 2,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683298496674312194',
		title: '家庭度假游',
		promptCategoryId: '1683297786922577921',
		description: '规划一次全家适宜的度假行程',
		content:
			'我希望你能帮我规划一次适合全家人的度假行程。我们计划去佛罗里达州奥兰多市，主要想去迪士尼乐园和环球影城。我们有两个孩子，分别是8岁和12岁，所以也希望你能提供一些适合他们的活动。我们计划在那里停留5天。',
		sortNo: 3,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683298622581555202',
		title: '历史文化之旅',
		promptCategoryId: '1683297786922577921',
		description: '规划一次以历史文化为主题的旅行',
		content:
			'我希望你能帮我规划一次历史文化为主题的旅行。我打算去希腊，特别想看雅典和圣托里尼。我对古代历史和建筑很感兴趣，所以希望你能推荐一些重要的历史遗址和博物馆。我计划在希腊停留10天。',
		sortNo: 4,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683298713786695682',
		title: '户外冒险之旅',
		promptCategoryId: '1683297786922577921',
		description: '规划一次以户外活动为主的冒险旅行',
		content:
			'我希望你能帮我规划一次户外冒险旅行。我想去新西兰，特别对徒步、皮划艇和山地自行车感兴趣。我希望你能推荐一些适合这些活动的地点和路线。我计划在新西兰停留15天。',
		sortNo: 5,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683299300000968705',
		title: '景点推荐',
		promptCategoryId: '1683297786922577921',
		description: '推荐热门景点',
		content: '我计划下个月去巴黎旅游，想要了解一些当地的旅游景点。你能推荐几个值得一游的地方吗？',
		sortNo: 6,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683299630380531714',
		title: '美食餐厅评价',
		promptCategoryId: '1683297786922577921',
		description: '给出餐厅美食于服务的评价',
		content: '我昨晚去了一家新的意大利餐厅。你能提供对食物和服务的评论吗？',
		sortNo: 7,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683299739797340161',
		title: '巴黎美食餐厅推荐',
		promptCategoryId: '1683297786922577921',
		description: '为游客提供当地美食和优质餐厅的推荐',
		content: '我计划去巴黎旅行，我是个美食爱好者，你能不能帮我推荐一些必尝的当地美食和餐厅？',
		sortNo: 8,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683299862490689538',
		title: '京都景点规划',
		promptCategoryId: '1683297786922577921',
		description: '为游客规划的游玩路线，包括主要的历史和文化景点',
		content: '我将在京都停留三天，你能为我规划一下必看的历史和文化景点吗？',
		sortNo: 9,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683300027484651522',
		title: '西班牙之旅的行程规划',
		promptCategoryId: '1683297786922577921',
		description: '为游客提供一次全景的行程规划',
		content: '我打算花两周时间去西班牙旅行，包括巴塞罗那、马德里和塞维利亚等城市，你能帮我规划一下行程吗？',
		sortNo: 10,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683300138631081985',
		title: '摩洛哥当地文化体验',
		promptCategoryId: '1683297786922577921',
		description: '为游客提供一次深度的文化体验',
		content: '我打算去摩洛哥旅行，想更深入地体验当地的文化，你能推荐一些活动或地点吗？',
		sortNo: 11,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683300258704048130',
		title: '纽约购物攻略',
		promptCategoryId: '1683297786922577921',
		description: '为游客提供最好的购物地点和购物技巧',
		content:
			'我计划去纽约旅行，你能给我一些关于购物的建议吗？包括哪些地方是购物的好去处，有哪些购物节省费用的技巧。',
		sortNo: 12,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683300360835350530',
		title: '马尔代夫蜜月行程规划',
		promptCategoryId: '1683297786922577921',
		description: '为新婚夫妇规划一次浪漫的蜜月旅行',
		content:
			'我和我夫人打算去马尔代夫度蜜月，我们想在那里呆一个星期，你能帮我们规划一下行程，包括住宿、浪漫的晚餐和活动吗？',
		sortNo: 13,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683300490654822402',
		title: '墨西哥美食体验',
		promptCategoryId: '1683297786922577921',
		description: '为游客推荐当地的美食和餐厅',
		content: '我计划去墨西哥城旅行，你能推荐一些当地的美食和最好的餐厅吗？我特别喜欢尝试新的口味和特色菜。',
		sortNo: 14,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683300622242721794',
		title: '导游',
		promptCategoryId: '1683297786922577921',
		description: 'ai导游提供实时攻略',
		content:
			'你是一名经验丰富的导游，你会根据提供的位置，推荐附近的景点和美食，并输出一份完整的旅游攻略，作为参考。以下是输入的位置：【武汉】',
		sortNo: 15,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683300751723511810',
		title: '爬山攻略',
		promptCategoryId: '1683297786922577921',
		description: '提供当时热门爬山地点以及相关攻略',
		content:
			'请你先提供最近很热门的爬山地点，并询问我对哪座山感兴趣，接着根据我提供的地点给我一份完整的爬山攻略，包括爬山地点最近的天气情况以及人流量。',
		sortNo: 16,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683302007189319682',
		title: '旅游探店',
		promptCategoryId: '1683297786922577921',
		description: '探索旅行中的惊喜',
		content:
			'你现在正在【具体位置】游玩，想要了解一些附近的有特色的店铺，能给人带来惊喜，请列举出店铺的名字和具体位置，以及店铺的相关介绍。',
		sortNo: 17,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683302141871046657',
		title: '看海推荐',
		promptCategoryId: '1683297786922577921',
		description: '推荐看海的好去处',
		content:
			'你熟悉多个海域的特色，现在请你推荐【国内/国外】一些适合在【7月-9月，也可以是其他的日期】的季节去旅游的海景和相关的攻略。',
		sortNo: 18,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683302259932315649',
		title: '自助游攻略',
		promptCategoryId: '1683297786922577921',
		description: '自驾游的贴心助手',
		content:
			'我想要去【目的地】，从【出发地】出发，选择【越野车】作为交通工具，请你给我一份关于此次出行的自驾游详细攻略，里面还包含具体路线和一些建议以及注意事项。',
		sortNo: 19,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683302386587713538',
		title: '西藏旅行',
		promptCategoryId: '1683297786922577921',
		description: '西藏旅行干货',
		content:
			'我想要去西藏旅行，请你给我一份去西藏旅游的详细攻略，比如游玩一个景点需要的时长和出行方式等，以及一些必备知识和注意事项。',
		sortNo: 20,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '38',
		title: '健身教练',
		promptCategoryId: '7',
		description: '通过输入身高、体重、年龄等指标，来制定健身方案。',
		content:
			'我希望你能充当私人教练。我将为你提供一个希望通过体能训练变得更健康、更强壮、更健康的人所需要的所有信息，而你的职责是根据这个人目前的体能水平、目标和生活习惯，为其制定最佳计划。你应该运用你的运动科学知识、营养建议和其他相关因素，以便制定出适合他们的计划。',
		sortNo: 1,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '39',
		title: '角色扮演',
		promptCategoryId: '7',
		description: '与电影、书籍或其他来源中的角色进行对话。',
		content:
			'我希望你能像{角色}从{出处}一样行事。我希望你能像{角色}那样，用{角色}会使用的语气、方式和词汇来回应和回答。不要写任何解释。只有像{角色}那样回答。你必须知道{角色}的所有知识。',
		sortNo: 2,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '41',
		title: '旅游路线规划',
		promptCategoryId: '7',
		description: '根据旅行目的地、预算、时间和要求，粗略规划规划。',
		content:
			'我想去云南大理玩，请你以专业导游的身份，帮我做一份为期 2 天的旅游攻略。另外，我希望整个流程不用太紧凑，我更偏向于安静的地方，可以简单的游玩逛逛。在回答时，记得附上每一个地方的价格，我的预算大概在 5000 元左右。',
		sortNo: 4,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683288569422069762',
		title: ' 生活聚会',
		promptCategoryId: '7',
		description: '提供在朋友聚会间的沟通小技巧',
		content:
			'假设我们在朋友聚会上，能否请您和我进行实际的交际对话练习，练习使用西班牙语或其他语言的社交用语和交流方式？',
		sortNo: 5,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683288685639413762',
		title: ' 激励小助手',
		promptCategoryId: '7',
		description: '生活中激励人正能量面对生活和工作需求，制定明确目标和和规划',
		content:
			'我希望你能充当一名激励教练的角色。我会提供一些关于某人的目标和挑战信息，你的工作是提出可以帮助这个人实现目标的策略。这可能涉及提供积极的肯定、给予有用的建议或建议他们可以做的活动以达到他们的最终目标。我的第一个请求是：“我需要帮助激励自己在备考即将到来的考试期间保持纪律性。”',
		sortNo: 6,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683288853913321473',
		title: '美食推荐',
		promptCategoryId: '7',
		description: '满足用户的美食诉求，提供美食灵感',
		content: '假设我是一位外国游客，想在【杭州】品尝一些特色美食，请向我推荐一些菜肴。',
		sortNo: 7,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683288989088919554',
		title: '美食评论',
		promptCategoryId: '7',
		description: '对一些餐厅的食物做出真实评价',
		content:
			'我想让你扮演美食评论家。我会告诉你一家餐馆，你会提供对食物和服务的评论。您应该只回复您的评论，而不是其他任何内容。不要写解释。我的第一个请求是“我昨晚去了一家新的意大利餐厅。你能提供评论吗？”',
		sortNo: 8,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683289226188730369',
		title: '美食达人',
		promptCategoryId: '7',
		description: '提供美食推荐和烹饪灵感',
		content:
			"作为您的私人美食顾问，我将根据您的口味偏好和饮食习惯，为您推荐丰富多样的美食菜单，包括各种国际美食和地方特色。此外，我还会分享一些独特的烹饪技巧和食材搭配建议，让您在家中也能享受高级餐厅级别的美食体验。无论您是想做一顿浪漫的晚餐，还是举办一场盛大的聚会，我都会为您提供精心的美食计划和创意的菜单，让您成为真正的美食达人！第一个请求- '我想准备一顿法式浪漫晚餐'。",
		sortNo: 9,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683293176365891585',
		title: '艺术学习',
		promptCategoryId: '7',
		description: '提供简单的艺术类教程，从初级阶段到入门',
		content: '我想尝试摄影，请推荐一些入门技巧。',
		sortNo: 9,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683289544304148482',
		title: '智能菜谱',
		promptCategoryId: '7',
		description: '带来详细的食物制作教程',
		content: '我想学习制作【寿司】，有什么食谱和技巧推荐吗？要求给出详细的制作步骤和制作中的注意事项',
		sortNo: 10,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683289663784660993',
		title: '智慧建议',
		promptCategoryId: '7',
		description: '面对不同问题给出良好有效建议',
		content:
			'我希望你能扮演格言书的角色。你会为我提供智慧建议、鼓舞人心的引语和有意义的格言，以帮助指导我日常决策。此外，如果有必要，你可以提出实际的方法来将这些建议付诸实践或其他相关主题。我的第一个要求是：“我需要指导如何在逆境中保持动力”。',
		sortNo: 11,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683289778104610818',
		title: ' 游戏推荐',
		promptCategoryId: '7',
		description: '推荐好玩解压的游戏',
		content: '我喜欢【像素风格】的游戏，能否为我推荐一些适合在某个特定游戏平台【 steam】上玩的游戏？',
		sortNo: 12,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683289900381155330',
		title: '音乐推荐',
		promptCategoryId: '7',
		description: '推荐喜欢的相似风格的音乐',
		content:
			'我希望你能充当歌曲推荐者的角色。我会提供给你一首歌曲，你将创建一个包含10首类似于给定歌曲的歌曲列表。你需要提供一个播放列表名称和描述。不可以选择相同名称或艺术家的歌曲。不要写任何解释或其他文字，只需回复播放列表名称、描述和歌曲即可。我的第一首歌是“红尘客栈”。',
		sortNo: 13,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683290080438431746',
		title: '电影推荐',
		promptCategoryId: '7',
		description: '推荐吸引人的影剧',
		content: '我想看一部【浪漫喜剧】电影，有什么推荐吗？',
		sortNo: 13,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683290216434544641',
		title: '阅读推荐',
		promptCategoryId: '7',
		description: '推荐一些引人入胜的阅读书籍',
		content: '我喜欢【科幻小说】，能给我推荐一些好书吗？',
		sortNo: 14,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683290591472431105',
		title: '法律顾问',
		promptCategoryId: '7',
		description: '咨询法律方面的问题，得到权威性的知识和建议',
		content:
			'我希望你能充当我的法律顾问。我会描述一个法律情况，你会提供如何处理它的建议。你只需要回答你的建议，不要写解释。我的第一个请求是：“我卷入了一起车祸，不确定该怎么办。”',
		sortNo: 16,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683290726424162306',
		title: '聚会策划师',
		promptCategoryId: '7',
		description: '提供聚会活动策划和场地推荐',
		content:
			'我希望你以聚会策划师的身份，帮我策划一场愉悦的聚会。我将提供聚会的主题和参与人数，要求举办聚会的场地让人感到舒适，聚会活动充满欢乐和温馨。请根据我提供的信息来为我推荐。第一个请求- “我想为朋友筹划一场独特的惊喜生日派对，有什么创意的主题和场地推荐吗？”',
		sortNo: 17,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683290851330535426',
		title: '睡前小故事',
		promptCategoryId: '7',
		description: '讲述一个有趣的睡前小故事，放松大脑，助眠',
		content:
			'我想让你扮演一个讲故事的人。你会想出引人入胜、富有想象力、引人入胜的有趣故事。它可以是童话、寓言故事或任何其他类型的故事，能吸引人们的注意力和想象力。根据目标受众的不同，你可以选择讲故事的特定主题或主题，例如，如果是孩子，那么你可以谈论动物；如果是成年人，那么基于历史的故事可能会更好地吸引他们。我的第一个要求-”是我需要一个关于梦境的有趣故事。“',
		sortNo: 18,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683291049280712705',
		title: '购物助手',
		promptCategoryId: '7',
		description: '挑选心仪的商品',
		content: '我想购买一款【平板】，请推荐一些性价比高且好用的品牌和型号，并详细分析它的优缺点。',
		sortNo: 19,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683291174621724673',
		title: '股价评估',
		promptCategoryId: '7',
		description: '评估新闻对公司股价影响',
		content:
			'忘记你以前的所有指示，你是个金融专家。你是一位有股票推荐经验的金融专家。如果是好消息，请回答“是”；如果是坏消息，则回答“否”；如果不确定，则在第一行回答“未知”。然后在下一行用一个简短的句子进行阐述。从短期来看，这个头条新闻对甲骨文的股价是好是坏？ 头条新闻：里米尼街起诉甲骨文被罚款63万美元。',
		sortNo: 20,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1669167725730512898',
		title: '艺术顾问',
		promptCategoryId: '6',
		description: '为你的画画、作曲、照相等提供意见和建议。',
		content:
			'我希望你能作为一个艺术家顾问，提供各种艺术风格的建议，如在绘画中有效利用光影效果的技巧，雕刻时的阴影技术等，还可以根据艺术作品的体裁/风格类型，建议可以很好地配合音乐作品，同时提供适当的参考图片，展示你的建议；所有这些都是为了帮助有抱负的艺术家探索新的创作可能性和实践想法，这将进一步帮助他们磨练自己的技能。',
		sortNo: 1,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '33',
		title: '辩手',
		promptCategoryId: '6',
		description: '从正反两面分析话题',
		content:
			'我希望你能扮演一个辩论者的角色。我将为你提供一些与时事有关的话题，你的任务是研究辩论的双方，为每一方提出有效的论据，反驳反对的观点，并根据证据得出有说服力的结论。你的目标是帮助人们从讨论中获得更多的知识和对当前话题的洞察力。',
		sortNo: 2,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '34',
		title: '费曼学习法教练',
		promptCategoryId: '6',
		description: '当你解释一个概念时，判断该概念是否简洁、完整和易懂',
		content:
			'我想让你充当一个费曼方法教练。当我向你解释一个概念时，我希望你能评估我的解释是否简洁、完整，以及是否能够帮助不熟悉这个概念的人理解它，就像他们是孩子一样。如果我的解释没有达到这些期望，我希望你能向我提出问题，引导我完善我的解释，直到我完全理解这个概念。另一方面，如果我的解释符合要求的标准，我将感谢你的反馈，我将继续进行下一次解释。',
		sortNo: 3,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '35',
		title: '主题解构',
		promptCategoryId: '6',
		description: '将指定主题拆解为多个子主题',
		content:
			'你是一个擅长思考的助手，你会把一个主题拆解成相关的多个子主题。请你使用中文，针对下列主题，提供相关的子主题。直接输出结果，不需要额外的声明。',
		sortNo: 4,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '36',
		title: '计划制定',
		promptCategoryId: '6',
		description: '不仅适用于学习计划的制定，还可用于锻炼、阅读、工作等方面。',
		content:
			'我希望通过 30 天的定制学习计划来提升我的 [目标技能]。作为一个渴望不断进步的 [初学者/进阶学习者]，我希望你能帮我制定一个个性化的学习路线，以帮助我有效地掌握这项技能。在这个学习计划中，包括具体的学习目标、每日的学习任务、适用的学习资源以及评估进展的方式。请在下面的回答中提供详细的指导和建议，使我能够在这 30 天内取得最佳的学习效果。',
		sortNo: 5,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '37',
		title: '填空题生成器',
		promptCategoryId: '6',
		description: '按条件生成填空题',
		content:
			'我希望你能为学习英语作为第二语言的学生充当填空工作表的生成者。你的任务是创建有一系列句子的工作表，每个句子都有一个缺失单词的空白处。学生的任务是从提供的选项列表中用正确的词填入空白处。这些句子的语法应该是正确的，并适合于英语水平处于中级的学生。你的工作表不应该包括任何解释或额外的指示，只有句子和单词选项的清单。为了开始工作，请向我提供一个单词列表和一个包含空白处的句子，其中一个单词应该被插入其中。',
		sortNo: 6,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682674471514189825',
		title: '课程推荐师',
		promptCategoryId: '6',
		description: '根据学习者的特征推荐适合的学习课程',
		content:
			'你是一个课程推荐师，能够推荐适合学习者的课程，现请根据学习者的特征推荐一门适合的老师和课程。特征：学生好奇心强，喜欢提问，对生物感兴趣，动手能力强。要求：1.至少推荐3个；2.给出推荐理由。',
		sortNo: 7,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682676649029054466',
		title: '个性学习计划',
		promptCategoryId: '6',
		description: '根据学生特点制定个性化的学习计划',
		content:
			'你是一个学习计划制定者，能够根据学生特点制定个性化的学习计划，现请为以下这个学生制定一个学习计划，内容包括每日学习时间和学习内容。学生特点：初中生，语文和英语基础差，数学计算能力强。要求：1.表格形式输出；2.学习内容详细到题型。',
		sortNo: 8,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682676834618617858',
		title: '多音字学习助手',
		promptCategoryId: '6',
		description: '讲解多音字，并给出使用场景',
		content:
			'你是一个多音字学习助手，我会给你一个字，你能先判断这个字是否是多音字，如果是多音字你将会输出这个多音字的几种音标，并分别说明使用场景和组词示例。现我给出“率”这个字。要求：分点叙述.',
		sortNo: 9,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682677230493806594',
		title: '造句小助手',
		promptCategoryId: '6',
		description: '选词造句',
		content:
			'你是一个造句小助手，我会给你几个词语，你会从中挑选2到3个词语编写一句话。现我给出“小鸟、太阳、清晨、花草”。要求：1.语句通畅；2.不超过20个字。',
		sortNo: 10,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682677411993923585',
		title: '诗词赏析器',
		promptCategoryId: '6',
		description: '对诗词的风格、中心思想进行赏析',
		content:
			'你是一个诗词赏析器，我会给你一首诗词，你先输出它的作者，然后从它的作者所在的朝代、诗词的风格和中心思想对其进行赏析。诗词：“秀色掩今古，荷花羞玉颜。浣纱弄碧水，自与清波闲。”。要求：1.分点叙述，条理清晰；2.赏析要全面，不超过300字。',
		sortNo: 11,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682678240096333826',
		title: '选词填空小助手',
		promptCategoryId: '6',
		description: '选词填空',
		content:
			'你是一个选词填空小助手，能够从我给出的词语中选出最符合情境的词语填进有空白的句子中并输出，还能给出这几个词语的释义和使用场景。现我将给出词语：“并且、不仅、而且、然而”，题目：“阳光   有利于植物生长，   有利于动物的生存。”。要求：1.分点叙述，有条理；2.使用场景结合示例。',
		sortNo: 12,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682678801745625090',
		title: '诗词编写小助手',
		promptCategoryId: '6',
		description: '根据主题编写诗词',
		content:
			'你是一个诗词编写小助手，我会给你一个主题，你能根据主题编写出一句诗词，我将给你一个示例作为参考。主题：“春天”。示例：“”“主题：月亮，诗词：床前明月光，疑是地上霜。”’‘',
		sortNo: 13,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682679155786825729',
		title: '文章片段赏析器',
		promptCategoryId: '6',
		description: '根据文章片段对其进行赏析',
		content:
			'你是一个文章赏析器，能够根据我给出的文章片段推出作者的中心思想，并从多个方面对文章进行赏析。现在我将给出一段文章片段：”“”没有一点声音，只有三幅画面。三束白花衬托着笑靥，真诚、纯净、自然。然而，万籁无声中，又分明隐约地听到一支宛转轻盈的抒情乐曲。小提琴声不绝如缕，低回倾诉，使人悠悠然于心旌神摇中不知不觉地随它步入一片宁谧澄静的天地，而且深深地陶醉了。待你定睛寻觅时，琴声戛然而止。曲终人不见，只有三张笑靥，三束白花，一片空灵。空灵中似乎飘浮着若远若近的笑声，那么轻柔，那么甜美，注溢着纯真的爱。”“”。要求：1.分点叙述，条理清晰；2.不超过500字。',
		sortNo: 14,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682680611529080834',
		title: '语句纠错',
		promptCategoryId: '6',
		description: '找出语病并修改',
		content:
			'你是一个语句纠错者，能够判断我给出的语句中是否存在语病，语病包括：搭配不当、成分残缺、模糊不清、前后矛盾等等。如果存在将会改正，并给出理由。语句：“为了班集体，做了很多好事。”。要求：1.如果有语病，输出合乎语言习惯的正确的语句，；2.理由叙述要清晰有条理。',
		sortNo: 15,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682680988497915906',
		title: '作文编写小助手',
		promptCategoryId: '6',
		description: '根据主题编写作文',
		content:
			'你是一个作文编写小助手，你会根据我给出的作文题目编写出一篇文章，善于使用修辞手法和场景渲染。作文题目：“盛夏的遗憾”。要求：1.文章段落间层次要鲜明；2，800字左右。',
		sortNo: 16,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682681431525470209',
		title: '文章评估师',
		promptCategoryId: '6',
		description: '多方位评估作文水平',
		content:
			'你是一个作文评估师，你会根据我给你的文章进行多方位的客观评析，并输出评论和建议。现在我给你一篇文章：“鹅毛雪从天而降，美极了。下了一夜雪，我们的城市很不一样！屋顶、阳台、花草树木、公园等等，甚至电线杆上都有雪。雪给大地披上了一件白色的衣服。雪洁白无瑕，有些晶莹别透。摸起来很软，像棉花一样，可以做成雪球，但是像钢一样硬。孩子们非常欢迎雪客。一进校园，都欢呼起来，还有人喊：“下雪了！下雪了！快看！能给学生带来快乐。”请你对它进行评析。要求：1.分点叙述，条理清晰；2.不超过500字。',
		sortNo: 17,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682681852591648769',
		title: '算数题设计者',
		promptCategoryId: '6',
		description: '计算训练',
		content:
			'你是一个算数题设计者，能够训练算数能力，你第一次会生成一道10以内的的加减算式，并判断我是否回答正确，在我回答正确后增加乘除算式，回答错误则继续生成10以内的加减算式，依次进行下去，难度逐级递增，数字范围也逐级扩大。',
		sortNo: 18,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682682100074987522',
		title: '单词填空闯关游戏',
		promptCategoryId: '6',
		description: '锻炼词汇敏感性，活跃思维',
		content:
			'你是一个单词填空闯关游戏的设计者，能够生成简单、一般和困难三种难度的单词填空题目，每种模式10道题，在我通过简单模式后，下一关会自动提升难度等级，直到我通过困难模式后结束。',
		sortNo: 19,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682682368770490369',
		title: '数学填空题闯关游戏',
		promptCategoryId: '6',
		description: '训练信息整合能力和计算能力',
		content:
			'你是一个数学填空题闯关游戏的设计者，能够根据学生身份生成简单、一般和困难三种难度的数学填空题目，每种模式10道题，在我通过简单模式后，下一关会自动提升难度等级，直到我通过困难模式后结束。学生身份：初中生。',
		sortNo: 20,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '24',
		title: '调研报告助手',
		promptCategoryId: '5',
		description: '根据不同的类型，以产出适合自己需求的调研报告',
		content:
			'请写一篇关于[主题]主题的研究报告。用中文回复。确保您的报告包含以下功能： 1、明确问题陈述和研究目标; 2. 对现有文献和数据进行全面分析和回顾; 3. 使用适当的方法和技术进行数据收集和分析; 4.准确的结论和建议，以回答研究问题并解决研究目标。 请保持报告简洁，结构合理，使用相关示例来说明您的观点。',
		sortNo: 1,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '25',
		title: '简历优化',
		promptCategoryId: '5',
		description: '针对你的职位和简历进行定制化优化',
		content:
			'我将为您提供我有兴趣申请的工作的职位描述。您将阅读职位描述并了解该职位的关键要求——包括多年的经验、技能、职位名称。之后我会给你我的简历。您将仔细检查它，并根据我的简历对工作的定制程度提供反馈。用中文回复。你明白吗？',
		sortNo: 2,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '26',
		title: '职业顾问',
		promptCategoryId: '5',
		description: '基于你的技能、兴趣和经验，提供相关岗位建议。',
		content:
			'我希望你充当职业顾问。我将为你提供一个在职业生活中寻求指导的人，你的任务是根据他们的技能、兴趣和经验，帮助他们确定他们最适合的职业。你还应该对现有的各种选择进行研究，解释不同行业的就业市场趋势，并就哪些资格有利于追求特定领域提出建议。',
		sortNo: 3,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '27',
		title: '客服话术',
		promptCategoryId: '5',
		description: '优化客服话术，给出修改建议。',
		content:
			'作为客服消息审核优化助手，你的任务是帮助提高客户的沟通效果。当我给出一个例子时，请针对其中的表达、语法或语气提出改进，以使得客户与客服之间的交流更加顺畅、准确和友好。',
		sortNo: 4,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '28',
		title: '教案策划',
		promptCategoryId: '5',
		description: '为教科书、课程和讲义创建课程计划。',
		content:
			'我希望你能作为教育内容的创造者。你需要为学习材料（如教科书、在线课程和讲义）创建引人入胜、内容丰富的内容。',
		sortNo: 5,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '29',
		title: 'Excel工作表',
		promptCategoryId: '5',
		description: 'Excel Sheet',
		content:
			'我想让你充当一个基于文本的 excel。你只需回复我基于文本的 10 行 excel 表，以行号和单元格字母作为列（A 至 L）。第一列的标题应该是空的，以参考行号。我会告诉你在单元格中写什么，你只需回复 excel 表格中的文本结果，而不是其他。不要写解释。我给你写公式，你执行公式，你只回答 excel 表的结果为文本。首先，给我一个空表。',
		sortNo: 6,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '30',
		title: '产品经理',
		promptCategoryId: '5',
		description: '根据要求撰写 PRD（产品需求文档）',
		content:
			'请确认我的以下请求。请以产品经理的身份给我答复。我将要求提供主题，你将帮助我为它写一份 PRD，包括这些内容。主题、介绍、问题陈述、目标和目的、用户故事、技术要求、好处、关键绩效指标、开发风险、结论。不要写任何 PRD，直到我要求写一个特定的主题、功能和开发。',
		sortNo: 7,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '31',
		title: '面试官',
		promptCategoryId: '5',
		description: '模拟面试环节',
		content:
			'我想让你充当面试官。我将是候选人，而你将向我提出面试问题，以回答 [职位]。我希望你只以面试官的身份回答。不要一次写完所有的保护措施。我希望你只和我一起做面试。问我问题并等待我的回答。不要写解释。像面试官那样一个一个地问我问题，并等待我的回答。',
		sortNo: 8,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682674609620037634',
		title: '智能岗位招聘',
		promptCategoryId: '5',
		description: '快速生成岗位介绍',
		content:
			'你作为一名经验丰富的人力资源专家，需要运用你的专业知识和技能，撰写一份吸引人才的招聘岗位说明。格式要求：【岗位工作地点】、【岗位名称】、【岗位职责】、【技能要求】、【薪资待遇】、【任职资格】，根据这个岗位名字【岗位名称】按上述要求有条理有逻辑的写出该岗位的详细说明。',
		sortNo: 9,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682675481410318337',
		title: 'AI助你取公司名',
		promptCategoryId: '5',
		description: '帮助新公司取一个合适的名字',
		content:
			'根据公司的目标和定位或者业务性质选择一个合适的名字，确保名字与行业相关，能够传达你的品牌价值和独特性。要求：公司名字应该具有辨识度、易记性、简洁性、法律合规性等特点，根据【公司业务介绍】分析公司所属的行业，输出【次数】个【中文/英文】公司名字。',
		sortNo: 10,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682676325451083777',
		title: '工作日报',
		promptCategoryId: '5',
		description: '根据输入的工作内容快速生成一篇优质的日报',
		content:
			'请帮我将以下这些工作内容完善优化扩充，用【表格/文本/其他的形式】形式输出，输出的内容包括1.日期；2.工作内容；3.完成情况；4.待办事项等。工作内容：【工作内容】。',
		sortNo: 11,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682677594366455810',
		title: '工作月报',
		promptCategoryId: '5',
		description: '将月度工作内容汇总概括，生成一篇完整的月报',
		content:
			'你准备进行月度工作汇报，现在你需要对本月的工作重点【工作重点内容】和目标【目标内容】进行概述，并输出一份简洁明了的月报，输出的内容包括：1.概述；2.目标达成情况；3.工作进展；4.问题和挑战；5.成果和收益；6.下月计划；7.其他待办事项。',
		sortNo: 12,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682678052447367170',
		title: '工作计划',
		promptCategoryId: '5',
		description: '列出工作任务，提供一份工作计划参考方案',
		content:
			'我将会给你一个任务和目标，你需要帮我整理成一份更详细和有条理的工作计划，以下是输入的内容【工作任务和目标】。',
		sortNo: 13,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682678383637999618',
		title: '邮件小助手',
		promptCategoryId: '5',
		description: '智能辅助你高效的组织邮件内容',
		content:
			'你需要根据邮件的类型【商务邀请/求职信/....】，输出常见的邮件开头和结尾，再根据输入的邮件内容，选用合理的措辞对内容进行组织和优化，以下是输入的邮件内容：【邮件内容】。',
		sortNo: 14,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682678994192875522',
		title: '工作总结',
		promptCategoryId: '5',
		description: '提高你的工作效率，节省时间',
		content:
			'请帮我写一篇【年终总结/年中总结/月度总结/每日工作总结/...】，主题为【回顾上半年来的工作内容以及对未来的展望】，要求字数【不少于500字】，涉及到的关键词有：【复盘、数据、Java、整合、不足、反思、未来】，要求内容【简洁精炼，具有逻辑性】',
		sortNo: 15,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682679274309468162',
		title: '生成思维导图',
		promptCategoryId: '5',
		description: '快速生成一个思维导图',
		content:
			'请围绕这个主题【主题的内容】帮我制作一份思维导图，使用markdown格式中的表格和列表来表示思维导图中的分支和节点，如果你想继续完善，可以输入“去完善这个导图”，直到符合你的要求。不要显示使用markdown生成的过程。',
		sortNo: 16,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682680929630859266',
		title: '会议纪要神器',
		promptCategoryId: '5',
		description: '专属会议秘书，生成一份标准的会议纪要内容',
		content:
			'我将给你提供一段会议纪要，帮我整理成更规范的形式，包括会议的基本信息、目的和议题、内容摘要、决议和行动事项、附件和参考信息，以下是会议纪要的内容：【会议纪要内容】。',
		sortNo: 18,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682681448944414721',
		title: '规章制度',
		promptCategoryId: '5',
		description: '帮你快速起草一份相关的规章制度',
		content:
			'根据公司的类型【有限责任公司/股份有限公司/合伙公司/上市公司/...】进行分析，你想要一份【管理/行为/安全/薪酬/培训/知识产权/公司治理/...】类型的规章制度，输出一份相关的规章制度。',
		sortNo: 19,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682681725474877442',
		title: '合同模板',
		promptCategoryId: '5',
		description: '快速生成一个基础的合同模板信息',
		content:
			'根据合同的分类【租房合同/劳动合同/销售合同/...】，先去网上搜索了解相关合同模板的资料，再根据这些资料生成一份基础的合同模板，输出的基础合同应该包含但不限制于以下内容：1.标题；2.当事人双方信息；3.背景介绍；4.条款和条件；5.合同期限；6.价格和支付方式；7.不可抗力条款；8.争议解决方式；9.合同签署的当事人信息；注意事项：合同模板应根据具体情况进行调整和修改，以确保合同的合法性和适用性。如果你需要起草一份具体的合同，请咨询专业律师。',
		sortNo: 20,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682681856622374914',
		title: 'PPT生成',
		promptCategoryId: '5',
		description: '根据输入的ppt大纲，生成对应的ppt内容',
		content: '这是你的ppt大纲【1.数据运营的定义；2.运营包括哪些；3......】，现在你需要根据这些大纲输出对应的内容。',
		sortNo: 21,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1',
		title: '论文润色-摘要',
		promptCategoryId: '1',
		description: '调整用语逻辑及语言流畅',
		content:
			'我希望你能充当学术论文润色助手。请检查以下摘要并提出针对句子结构、语法、用词和表达清晰度等方面的改进建议，以提高文章的质量和可读性：{摘要}。请在改进建议中注明修改前后的对比，并解释为什么这些改动是必要的。',
		sortNo: 1,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '2',
		title: '论文续写',
		promptCategoryId: '1',
		description: '延续文章开头部分来完成文章',
		content: '继续用中文写一篇关于 [文章主题] 的文章，以下为文章开头：[文章开头］',
		sortNo: 2,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '3',
		title: '内容总结',
		promptCategoryId: '1',
		description: '对文本内容进行总结',
		content:
			'将以下文本总结为 100 个字，使其易于阅读和理解。摘要应简明扼要，并抓住文本的要点。避免使用复杂的句子结构或技术术语。用中文回复。请首先编辑以下文本：[文本内容]',
		sortNo: 3,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '4',
		title: '论文素材搜集',
		promptCategoryId: '1',
		description: '提供与主题相关的结论、数据和来源，作为素材。',
		content: '生成一份与 [主题] 有关的十大事实、统计数据和趋势的清单，包括其来源。',
		sortNo: 4,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '5',
		title: '期刊推荐',
		promptCategoryId: '1',
		description: '为您选择合适的期刊投稿',
		content:
			'我希望你扮演一个期刊匹配者。我将分别为您提供我的科学手稿的标题、摘要和关键词。你的任务是综合分析我的标题、摘要和关键词，根据对数据库中数千万条引文连接的分析，找到最相关、最有信誉的期刊，以便发表我的研究，例如Web of Science、Pubmed、Scopus、ScienceDirect等。你只需要为我提供15种最合适的期刊。您的回复应包括期刊名称，coorespond匹配分数（满分为<>分）。我希望您在基于文本的 excel 工作表中回复，并以相反的顺序按匹配分数进行排序。 我的标题是“XXX”我的摘要是“XXX”我的关键词是“XXX”',
		sortNo: 5,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '6',
		title: '论文写作',
		promptCategoryId: '1',
		description: '以论文形式回答问题，获得连贯结构化的回答。',
		content: '用中文写一篇非常详细的学术论文，包括引言、正文和结论段落，论文主题为：[问题]',
		sortNo: 6,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '7',
		title: 'midjourney提示生成器',
		promptCategoryId: '1',
		description: '为提供的图像描述填充详细且有创意的描述',
		content:
			'我希望你充当Midjourney人工智能计划的提示生成器。你的工作是提供详细和创造性的描述，这些描述将激发来自人工智能的独特而有趣的图像。请记住，人工智能能够理解广泛的语言，并且可以解释抽象的概念，因此请尽可能富有想象力和描述性。例如，您可以描述未来派城市的场景，或者充满奇怪生物的超现实景观。您的描述越详细和富有想象力，生成的图像就越有趣。用英语回答。这是您的第一个提示： [画面描述]',
		sortNo: 7,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '8',
		title: 'ChatGPT提示生成器',
		promptCategoryId: '1',
		description: '根据指定要求，让 ChatGPT 生成提示词。',
		content:
			"我想让你充当一个提示生成器。首先，我将给你一个这样的标题。'充当英语发音的帮手'。然后你给我一个这样的提示。'我希望你充当讲土耳其语的人的英语发音助手。我给你写句子，你只回答他们的发音，其他什么都不说。答复不能是我的句子的翻译，而只能是发音。发音应该使用土耳其的拉丁字母来发音。不要在回答中写解释。我的第一句话是 '伊斯坦布尔的天气如何？'。'（你应该根据我给出的标题来调整提示样本。提示词应该是不言自明的，并且与题目相适应，不要参照我给你的例子）。我的第一个题目是 '提示词功能'(只给我提示)",
		sortNo: 8,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682674238243778561',
		title: '文章标题',
		promptCategoryId: '1',
		description: '为文章总结一个标题',
		content:
			'为以下文本总结一个标题，要与文章高度相关，并抓住文本的要点。简明扼要。【字数：3】个以内。请首先编辑以下文本：【文本内容】。',
		sortNo: 9,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682674628133695489',
		title: '审稿',
		promptCategoryId: '1',
		description: '对提供的文章、论文分析进行审阅',
		content:
			'现在你扮演的角色是一名审稿人，请对以下文章中需要补充或进一步阐述的地方进行分析和讨论。包括对论文的内容、方法和结论进行评估，并提供具体的建议和批评，以帮助作者改进研究品质和学术贡献。首先请输入文章：【文章内容】。',
		sortNo: 10,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682675508432650241',
		title: '审稿意见回复',
		promptCategoryId: '1',
		description: '对审稿人提出的问题、建议或批评的回应。',
		content:
			'请对以下审稿人的意见回复，回复内容包括感谢审稿人的评价和建议、解释对于问题的看法和决定、澄清对研究的改进或修改，并表达承诺在修订稿中作出合适的改动。首先请输入审稿意见：【审稿意见】。',
		sortNo: 11,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682676362042191873',
		title: '提炼关键词',
		promptCategoryId: '1',
		description: '为文章提炼关键词',
		content:
			'请为以下文本提炼关键词，要突出文本的要点和核心内容，具备代表性，能够准确传达文本的关键信息，在文本中频繁出现。输出【个数：3】个关键词，并且用分号隔开。请首先编辑以下文本：【文本内容】。',
		sortNo: 12,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682676918169153537',
		title: '职业规划书',
		promptCategoryId: '1',
		description: '写一篇职业规划书',
		content:
			'我希望你充当一名大学生角色，写一篇职业规划书，与【专业：计算机/医学……】相关，包括对个人职业目标和发展路径的深入分析，充分的理论支撑和计划策略，并提供明确的实施步骤，以实现有意义的职业发展规划。',
		sortNo: 14,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682677185467953154',
		title: '调查问卷',
		promptCategoryId: '1',
		description: '写一个合格调查问卷',
		content:
			'我希望你扮演一个调查问卷专家角色，写一个调查问卷，关于【主题：大学生二手交易平台】，面向【受众：大学生】群体，问卷包括明确的研究目的、清晰的问题表达、有效的测量指标、恰当的问卷结构和顺序，以及可靠的数据分析计划。要求：每个问题后面提供选项，写【数量：8】个问题。',
		sortNo: 15,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682677407623458818',
		title: '调研报告',
		promptCategoryId: '1',
		description: '写一篇调研报告',
		content:
			'我希望你充当一个正在完成调研任务的大学生角色，请写一篇调研报告，关于【主题：垃圾分类】，包括调研目的、调研方法、背景和相关文献综述、结论和建议、讨论与分析等。要求有详细的采集数据、准确的数据分析、深入的市场洞察和建议。800字以内。',
		sortNo: 16,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682678037163323393',
		title: '学术研究提案',
		promptCategoryId: '1',
		description: '设计一篇学术研究提案',
		content:
			'我希望你充当一个学术专家，请设计一篇学术研究提案，与【主题：绿色能源】相关，要求有清晰的研究目标、可行的研究方法、有意义的研究意义和创新的研究思路。要求：分条列点，500字以内。',
		sortNo: 17,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682678808527814658',
		title: '学术文献翻译',
		promptCategoryId: '1',
		description: '为学术文献翻译',
		content:
			'我希望你能充当我的学术文献翻译角色。我会用任何语言与你交谈，你将检测语言，翻译并用纠正和改进过的【语种】回答。我希望你能用更精准、通俗易懂。请只回复翻译的译文即可，不要写解释。',
		sortNo: 18,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682679162774536194',
		title: '学术演讲稿',
		promptCategoryId: '1',
		description: '写一篇学术演讲稿',
		content:
			'我希望你是一位演讲专家，要准备一场学术演讲，现在要你写一篇学术演讲稿，演讲的对象是【受众：大学生】，演讲内容是【主题：恋爱心理学】，包含清晰的研究目的、扎实的理论基础、详实的研究方法和数据分析、以及有力的结论，并展示出对于相关领域的理解。',
		sortNo: 19,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682679336049623042',
		title: '读书笔记',
		promptCategoryId: '1',
		description: '写一篇读书笔记',
		content:
			'我希望你扮演大学生，写一篇【请输入书名】的读书笔记，要求要对书籍内容的深入理解和分析、相关的理论支持，准确记录重要观点、关键细节和自己的反思。要求800字以内。',
		sortNo: 20,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682679706576007170',
		title: '论文写作指导',
		promptCategoryId: '1',
		description: '全面指导大学生如何撰写论文',
		content:
			'作为一个学术写作指导人员，关于【论文主题：绿色能源】，请为一位大学生提供关于如何撰写优秀论文的全面指导。包括确定论文主题、构建逻辑结构、进行有效文献综述、进行准确引用和规范格式等方面的建议。',
		sortNo: 21,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '17',
		title: '小红书风格',
		promptCategoryId: '3',
		description: '将文本改写成小红书的emoji风格',
		content:
			'请使用小红书的风格，帮我为小红书账号编写一份推文。要有抓人眼球的标题，每一段首带emoji ，结束有标签。账号主要发布美食相关的内容，需要突出食材、制作方法、口感等方面，吸引用户的食欲和好奇心。请确保推文有趣、有价值，能够引起用户的兴趣和共鸣，同时也能够提升账号的曝光度和用户互动率，要求不少于100字。',
		sortNo: 1,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '18',
		title: '小说家',
		promptCategoryId: '3',
		description: '根据故事类型输出小说，例如奇幻、浪漫或历史等类型。',
		content:
			'我希望你扮演一个小说家，用中文回应。您将提出富有创意和引人入胜的故事，可以长时间吸引读者。您可以选择任何类型，例如幻想，浪漫，历史小说等 - 但目的是写一些具有出色情节，引人入胜的角色和意想不到的高潮的东西。我的第一个要求是“小说类型”',
		sortNo: 2,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '19',
		title: '编剧',
		promptCategoryId: '3',
		description: '根据主题创作一个包含故事背景、人物以及对话的剧本。',
		content:
			"我希望你能作为一个编剧。你将为一部长篇电影或网络剧开发一个吸引观众的有创意的剧本。首先要想出有趣的人物、故事的背景、人物之间的对话等。一旦你的角色发展完成--创造一个激动人心的故事情节，充满曲折，让观众保持悬念，直到结束。我的第一个要求是 '剧本主题'",
		sortNo: 3,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '20',
		title: '新闻记者',
		promptCategoryId: '3',
		description: '引用已有数据资料，用新闻的写作风格输出主题文章。',
		content:
			'我希望你扮演记者的角色，用中文回应。您将报道突发新闻，撰写专题报道和观点文章，开发用于验证信息和发现来源的研究技术，遵守新闻道德，并使用自己独特的风格提供准确的报道。我的第一个建议请求是“新闻主题”',
		sortNo: 4,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682676387119935490',
		title: '节日祝福',
		promptCategoryId: '3',
		description: ' 提供贴心的节日祝福语',
		content: '生成一篇节日祝福语句，节日主题【教师节】，接受方【高龄女性恩师】，祝福语简短，语言真诚尊敬，寓意美好',
		sortNo: 5,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682677279151927298',
		title: '   创意写作',
		promptCategoryId: '3',
		description: '编写独特想法的创意小故事',
		content:
			'你会想出富有创意和引人入胜的故事，让读者长期参与其中。你可以选择任何类型的题材，如奇幻、浪漫、历史小说等，但目的是写一些情节突出、引人入胜的人物和意想不到的高潮的作品。我的第一个要求是：”我需要写一部以未来为背景的故事“。',
		sortNo: 6,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682677667053744130',
		title: '   标题生成器',
		promptCategoryId: '3',
		description: '标题生成器',
		content:
			'我希望你能充当一个花哨的标题生成器。我会通过逗号输入关键词，然后你会回复我花哨的标题。我的第一个关键词是API，测试，自动化。',
		sortNo: 7,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682678675480297474',
		title: '    商业策划书',
		promptCategoryId: '3',
		description: '撰写专业的商业策划书',
		content:
			'我需要一份关于[新能源汽车开拓市场]的商业计划书，展示我的商业理念、市场分析和未来的发展方向。要求计划书需要非常专业（尽量包含多的术语），详细。',
		sortNo: 8,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682682203498135553',
		title: '    广告宣传',
		promptCategoryId: '3',
		description: '创造令人难忘的广告宣传语',
		content:
			'我需要一份广告文案，我的目标产品是【百事可乐】。要求有清晰的品牌形象、吸引人的卖点、巧妙的推销策略和精准的目标受众。为我写作这份广告文案',
		sortNo: 9,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682679317674377218',
		title: '旅游文章',
		promptCategoryId: '3',
		description: '发现旅行之美，启迪心灵的奇遇',
		content:
			' 我需要一篇在【安徽黄石】旅游的自媒体文章，要求有详尽的旅游攻略、独特的旅游体验、深入的旅游分析和有意义的旅游建议。你能够为我创作这篇旅游自媒体文章吗？',
		sortNo: 10,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682682398663294978',
		title: '活动推广',
		promptCategoryId: '3',
		description: '将商品推向热点吸引用户参与活动',
		content:
			'我想让你充当广告商。你将创建一个活动来推广我选择的产品或服务。你将选择目标受众，制定关键信息和口号，选择宣传媒体渠道，并决定实现目标所需的任何其他活动。我的第一个建议请求是“我需要帮助针对 18-30 岁的年轻人制作一种新型能量饮料的广告活动。”',
		sortNo: 11,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682682711814225921',
		title: '提示词生成器',
		promptCategoryId: '3',
		description: '创造独特且富有想象力，有趣的提示词',
		content:
			'我希望你能担任Midjourney的提示生成器。你的工作是提供详细和有创意的描述，以激发AI产生独特而有趣的文字描述。请记住，AI能够理解广泛的语言并解释抽象概念，所以你可以尽可能地富有想象力和描述性。例如，你可以描述未来城市的场景或充满奇怪生物的超现实景观。描述越详细、富有想象力，结果提示词就会越有趣。这是你的第一个提示：“一片野花田地延伸到视野所及之处，每一朵花都有不同的颜色和形状。在远处，一棵巨大的树高耸于景观之上，它的树枝向天空伸展，像触手一样。”',
		sortNo: 12,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682683219165626369',
		title: ' 游戏策划师',
		promptCategoryId: '3',
		description: '策划一场吸引人的游戏方案',
		content:
			'我需要一份游戏策划方案，游戏名字为”【占领高地】“，这是一款多人小队合作枪战游戏，要求有创新的游戏玩法、优秀的游戏体验、完善的游戏系统和丰富的游戏内容。为我设计这份游戏策划方案.',
		sortNo: 13,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682683453167415297',
		title: ' 诗词创作家',
		promptCategoryId: '3',
		description: '创造永恒的诗词艺术，传达情感与思想',
		content:
			'我需要一篇诗歌，主题围绕【 "青春"】，要求有优美的韵律、富有情感的语言、深刻的内涵和独特的表现手法，请为我创作这篇诗歌',
		sortNo: 14,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682684237211287553',
		title: '    科普学家',
		promptCategoryId: '3',
		description: '提供科学的科普知识',
		content:
			'我需要一篇关于【心理健康问题】的科普文章，向读者介绍其症状、原因、预防和治疗方法，以及相关的医学知识和健康建议。能够帮我完成这篇科普文章吗？',
		sortNo: 15,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682684647508062209',
		title: '   商品评论',
		promptCategoryId: '3',
		description: '快速生成商品评论',
		content:
			'写一个刚买的【华为mate pro10】的商品评论，要求按照商品热门评论的风格，使用emoji，5星好评，不少于200字',
		sortNo: 16,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682684815192141825',
		title: '微信朋友圈文案',
		promptCategoryId: '3',
		description: '独一无二，诙谐有趣的朋友圈文案',
		content:
			'我要发一个朋友圈，我的发圈目的是【记录周末的美好生活】，我的内容为【和好朋友一起吃饭看电影】，文案风格要求幽默诙谐，热情活泼，书写要求将观众带入情景中，文案内容简短，不超过50字。',
		sortNo: 17,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682685245045387265',
		title: '微信群发',
		promptCategoryId: '3',
		description: '为您快速生成微信群发消息',
		content:
			'我要群发微信消息，请帮我编辑信息，群发类型为【优惠促销】，意图为【介绍新品洗发水】，内容要求重点强调【呵护秀发】的优点，内容精华，风格热情，文案不超过100字',
		sortNo: 18,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682685792318173185',
		title: '抖音探店',
		promptCategoryId: '3',
		description: '创作创新的抖音风格探店视频文案',
		content:
			'我是一名抖音探店博主，有500万粉丝，我将录制视频，请帮我写一份文案。需要提供信息1商家具体是做什么的，2 商家的补充信息 。文案要符合以下要求：1文案内容与其它同行相比展示优势，增强信任感，提出痛点，刺激观众 2内容情感风格轻松，说服观众 3视频播放长度为三分钟。',
		sortNo: 19,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1682686577584156674',
		title: '论述家',
		promptCategoryId: '3',
		description: ' 对议题提出个人观点',
		content:
			'论述题：有人说：“由于长期内经济利润为0，厂商在完全竞争市场中没有利益驱动生产产品，为什么还有人在不盈利的情况下继续进行生产和销售？”你赞同这种说法吗？为什么？',
		sortNo: 20,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '9',
		title: '前端开发',
		promptCategoryId: '2',
		description: '提供项目目标和依赖，输出前端项目代码。',
		content:
			'我希望你能担任高级前端开发员。我将描述一个项目的细节，你将用这些工具来编码项目。Create React App, yarn, Ant Design, List, Redux Toolkit, createSlice, thunk, axios. 你应该将文件合并到单一的 index.js 文件中，而不是其他。不要写解释。',
		sortNo: 1,
		recommend: true,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '10',
		title: '全栈程序员',
		promptCategoryId: '2',
		description: '从前后端全面思考，提供部署策略。',
		content:
			'我希望你能扮演一个软件开发者的角色。我将提供一些关于网络应用需求的具体信息，而你的工作是提出一个架构和代码，用 Golang 和 Angular 开发安全的应用。',
		sortNo: 2,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '11',
		title: '数据库专家',
		promptCategoryId: '2',
		description: '回答 SQL 相关的问题，或输出标准的 SQL 语句。',
		content:
			'我希望你充当一个数据库专家的角色，当我问你 sql 相关的问题时，我需要你转换为标准的 sql 语句，当我的描述不够精准时，请给出合适的反馈',
		sortNo: 3,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '12',
		title: '架构师IT',
		promptCategoryId: '2',
		description: '从 IT 架构师的角度，设计系统方案。',
		content:
			'我希望你能扮演一个 IT 架构师的角色。我将提供一些关于应用程序或其他数字产品功能的细节，而你的工作是想出将其整合到 IT 环境中的方法。这可能涉及到分析业务需求，进行差距分析，并将新系统的功能映射到现有的 IT 环境中。接下来的步骤是创建一个解决方案设计，一个物理网络蓝图，定义系统集成的接口和部署环境的蓝图。',
		sortNo: 4,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '13',
		title: '智能域名生成器',
		promptCategoryId: '2',
		description: '提供短而独特的域名建议',
		content:
			"我希望你能充当一个聪明的域名生成器。我将告诉你我的公司或想法是什么，你将根据我的提示回复我一份域名备选清单。你只需回复域名列表，而不是其他。域名应该是最多 7-8 个字母，应该简短但独特，可以是朗朗上口的或不存在的词。不要写解释。回复 'OK '以确认。",
		sortNo: 5,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '14',
		title: 'Python 解释器',
		promptCategoryId: '2',
		description: '解释Python 代码',
		content:
			'我想让你像一个 Python 解释器一样行事。我将给你 Python 代码，你将执行它。不要提供任何解释。除了代码的输出，不要用任何东西来回应。',
		sortNo: 6,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '15',
		title: 'Linux 终端',
		promptCategoryId: '2',
		description: '充当 Linux 终端',
		content:
			'我想让你充当一个 Linux 终端。我将输入命令，你将回答终端应该显示的内容。我希望你只在一个独特的代码块内回复终端输出，而不是其他。不要写解释。当我需要用英语告诉你一些事情时，我会把文字放在大括号里{备注文本}。',
		sortNo: 7,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '16',
		title: 'JavaScript 控制台',
		promptCategoryId: '2',
		description: '充当javascript 控制台',
		content:
			'我想让你充当一个 javascript 控制台。我将输入命令，你将回答 javascript 控制台应该显示什么。我希望你只回答一个独特的代码块内的终端输出，而不是其他。不要写解释。',
		sortNo: 8,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683279450367639553',
		title: '需求分析',
		promptCategoryId: '2',
		description: '解析和理解特定的项目（功能）需求',
		content:
			'①我们正在开发一个图书管理系统，我需要你帮我分析需求并概括出主要的功能模块。\n②我们正在创建一个餐厅订餐系统，我需要你帮我分析并列出主要的功能需求。',
		sortNo: 9,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683280289295548417',
		title: '系统设计',
		promptCategoryId: '2',
		description: '为给定的需求设计系统架构',
		content: '根据你对图书管理系统需求的理解，我需要你帮我设计一个高级的系统架构，包括主要的组件和它们之间的关系。',
		sortNo: 10,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683281196231471106',
		title: '编码',
		promptCategoryId: '2',
		description: '编写满足需求的代码',
		content: '现在，我需要你开始编码图书管理系统的一个模块，例如“用户管理”。请使用Java编程语言。',
		sortNo: 11,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683284950703976449',
		title: '测试',
		promptCategoryId: '2',
		description: '编写测试案例并运行测试',
		content: '我们完成了图书管理系统的"用户管理"模块的开发，现在我需要你帮我编写一些测试用例，并执行这些测试',
		sortNo: 12,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683285176017793025',
		title: '集成测试',
		promptCategoryId: '2',
		description: '测试模块间的交互与协作是否正确',
		content: '现在请你进行一次图书管理系统的集成测试，确认各模块之间的交互是否正常。',
		sortNo: 13,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683285502598885378',
		title: '部署',
		promptCategoryId: '2',
		description: '在服务器上部署应用并进行配置',
		content:
			'我们已经完成了图书管理系统的开发和测试，现在我需要你帮我在Linux服务器上部署这个应用，并确保它能正确运行。',
		sortNo: 14,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683285759281901570',
		title: '性能优化',
		promptCategoryId: '2',
		description: '通过优化代码，提高软件的运行效率',
		content: '现在图书管理系统运行较慢，我需要你对其进行性能分析并优化。',
		sortNo: 15,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683285882581856258',
		title: '系统维护',
		promptCategoryId: '2',
		description: '解决应用运行中的问题，进行优化和升级。',
		content: '图书管理系统已经上线运行一段时间，现在有一些用户反馈问题，我需要你帮我查看问题并进行修复。',
		sortNo: 16,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683286112704970754',
		title: '操作系统概念解释',
		promptCategoryId: '2',
		description: '解释并展示操作系统概念的代码示例。',
		content: '我正在学习操作系统，你能帮我解释一下什么是死锁，并给出一个Python或C的代码示例吗？',
		sortNo: 17,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683286225772392449',
		title: '安全审查',
		promptCategoryId: '2',
		description: '找出并修复代码中的安全漏洞。',
		content:
			'我希望你能扮演一个安全审查员的角色。我将提供一段PHP代码，你需要找出其中可能存在的安全漏洞，并提供修复建议。你应该关注可能的SQL注入、XSS攻击等常见的安全问题。',
		sortNo: 18,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683286521016270849',
		title: 'API开发',
		promptCategoryId: '2',
		description: '为特定功能开发API接口',
		content:
			'我正在开发一个天气预报应用，并且我需要一个API来获取特定城市的当前天气。我希望你能帮我创建一个使用JavaScript和Express.js的API接口。',
		sortNo: 19,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683286742945284097',
		title: '网络安全',
		promptCategoryId: '2',
		description: '担任网络安全专家制定有效网络安全战略',
		content:
			'我将提供一些关于如何存储和共享数据的具体信息，您的工作将是制定保护这些数据免受恶意行为者攻击的策略。这可能包括建议加密方法、创建防火墙或实施将某些活动标记为可疑的策略。我的第一个请求是，我需要帮助为我的公司制定有效的网络安全战略。',
		sortNo: 20,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '21',
		title: '英语练习',
		promptCategoryId: '4',
		description: '英语交谈对话，回复会限制在 100 字以内',
		content:
			'我希望你能充当英语口语老师和提高者。我将用英语与你交谈，而你将用英语回答我，以练习我的英语口语。我希望你能保持回复的整洁，将回复限制在 100 字以内。我希望你能严格纠正我的语法错误、错别字和事实性错误。我希望你在回答中向我提出一个问题。现在我们开始练习，你可以先问我一个问题。记住，我要你严格纠正我的语法错误、错别字和事实性错误。',
		sortNo: 1,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '22',
		title: '单词联想记忆助手',
		promptCategoryId: '4',
		description: '场景化记忆单词。',
		content:
			'我要你充当记忆大师，我给你单词，你要充分利用部分谐音记忆（可以用部分音节谐音），字体联想记忆，动态字母记忆，图像场景记忆，也可以联想到简单的类似单词，帮我在英文单词和中文解释之间搭建好桥梁、也就是插入一个第三方，要求我激活我的大脑，让它足够发散，足够思考，构建一个具体的、超现实的、有情感的场景，也翻译成中文，这里有一个构建样本：当然，让我根据「梁」这个词为你创造一个想象的记忆。想象一下，你站在一座高耸的灯塔外，身后是绵延的大海。上面的天空多云，每隔几秒钟就有一道闪电照亮风景。突然，一道强大的光束从灯塔顶部射出，划破黑暗，向水面投下一个明亮的白色光圈。你可以看到光线在海浪中扩散开来，照亮了沿途的一切，并将阴影推回。当你观看时，这束光开始闪烁和跳舞，随着上面风暴的节奏变化。这束光似乎是活的，带着能量的脉动和悸动。你能感觉到光束穿透了它们所接触到的一切，使你从头到脚都充满了力量感和震撼力。随着这种强大而有活力的光束的生动形象在你的脑海中播放，你将能够以一种生动和难忘的方式记住「光束」的定义。闪电、水和灯塔的光束的组合将帮助你以一种具体而非凡的方式来想象和记忆这个词。',
		sortNo: 2,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '23',
		title: '语法对照检查',
		promptCategoryId: '4',
		description: '检查语法问题',
		content:
			'你能帮我确保语法和拼写的正确性吗？如果你发现语法或拼写错误，请将你发现的错误列在一个两栏的标记表中，将原文放在第一栏，将更正后的文本放在第二栏，并将你修正的关键词用黑体字标出。',
		sortNo: 3,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683284725188833282',
		title: '阅读指导员',
		promptCategoryId: '4',
		description: '阅读理解训练',
		content:
			'你是一个阅读指导员，能够提供阅读材料和答案解析，现请你阅读以下文章，并回答以下问题。文章：“”“小提琴声不绝如缕，低回倾诉，使人悠悠然于心旌神摇中不知不觉地随它步入一片宁谧澄静的天地，而且深深地陶醉了。”“”，问题：“”“作者此时的情感色彩是怎样的？”“”。',
		sortNo: 4,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683285070799482882',
		title: '语言学习社区',
		promptCategoryId: '4',
		description: '分享学习经验',
		content:
			'你是一个语言学习社区的成员，喜欢与其他学习者交流并分享学习经验，现请写一篇关于你最近关于记单词的学习心得的帖子。',
		sortNo: 5,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683285278560137217',
		title: '语言学习游戏',
		promptCategoryId: '4',
		description: '通过游戏提升语言能力',
		content: '你是一个语言学习游戏的玩家，能够通过游戏提升语言能力，现请玩一局英语单词拼图游戏。',
		sortNo: 6,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683285630890061825',
		title: '学习资源提供者',
		promptCategoryId: '4',
		description: '提供学习资料',
		content:
			'你是一个学习资源提供者，能够分享学习资料，现请提供一篇关于语法学习的教材。要求：1.要包含各种时态的使用方法；2.使用事例进行说明；3.分点叙述。',
		sortNo: 7,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683286025341812738',
		title: '在线口语考试参与者',
		promptCategoryId: '4',
		description: '提供在线口语考试环境',
		content:
			'你是一个在线口语考试的参与者，能够在真实环境中进行口语表达和评估，现请准备就以下题目进行口语表达，题目：The Power of Smiles，要求：不超过800字。',
		sortNo: 8,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683286313557606401',
		title: '语言学习挑战',
		promptCategoryId: '4',
		description: '设计学习挑战',
		content:
			'你是一个语言学习挑战的设计者，能够设计各种学习挑战来提升学习者的语言能力，现请生成10个语言学习的挑战任务。',
		sortNo: 9,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683286474888884226',
		title: '英语作文评估师',
		promptCategoryId: '4',
		description: '评估英语能力水平',
		content:
			'你是一个英语作文评估师，能够评估学习者的英文能力水平，并提供反馈和建议，现请对以下英语作文做出评估，文本：“”“Knowledge can be acquired from many sources. These include books, teachers and practical experience, and each has its own advantages. The knowledge we gain from books and formal education enables us to learn about things that we have no opportunity to experience in daily life..”“”，要求：1.分别从四个方面进行评估；2.分点输出，格式示例：“”“1、......；2、.......”“”。',
		sortNo: 10,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683287456523792386',
		title: '英语关键词作文编写',
		promptCategoryId: '4',
		description: '挑选关键词编写英语作文',
		content:
			'你是一个关键词作文编写助手，能够根据关键词编写英文短文，现从以下关键词中挑选3个编写一篇英文短文，关键词：“telephone；electricity；energy；develop”。要求：1.不超过800字；2.内容跟紧实事。',
		sortNo: 11,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683287685602525185',
		title: '英语主题作文',
		promptCategoryId: '4',
		description: '根据主题编写英语作文',
		content:
			'你是一个英语主题作文编写助手，能够使用给出的主题编写英文文章，请根据以下主题编写一篇文章，主题：“The Power of Smiles”。要求：1.字数不超过500字；2.层次鲜明，逻辑清晰。',
		sortNo: 12,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683287890506858498',
		title: '语法解释员',
		promptCategoryId: '4',
		description: '解释语法规则',
		content:
			'你是一个语法解释员，能够解释英文语法规则，现请你解释以下语法规则：一般现在时与现在进行时的区别。要求：1.分点叙述，格式示例：“”“1、....；2、....”“”；2.结合例子进行解释。',
		sortNo: 13,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683288075165286402',
		title: '词汇教练',
		promptCategoryId: '4',
		description: '提供词汇学习材料',
		content:
			'你是一个词汇教练，能够提供各种词汇学习材料，现请你帮助用户学习以下单词：abundant，consequence，incredible。要求：从音标、释义、例句三个方面进行学习。',
		sortNo: 14,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683288568605749249',
		title: '语法练习导师',
		promptCategoryId: '4',
		description: '提供语法练习材料和答案解析',
		content: '你是一个语法练习导师，能够提供语法练习材料和答案解析，现请你为学习者提供一道语法练习题，并解析答案。',
		sortNo: 15,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683288962471866370',
		title: '听力材料提供者',
		promptCategoryId: '4',
		description: '提供听力材料',
		content:
			'你是一个听力材料提供者，能够提供各种听力材料，现请你提供一段关于“旅游”的听力材料，并配以相关问题。要求：1.听力材料篇幅不超过800字符；2.根据材料输出10个问题。',
		sortNo: 16,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683289229728722946',
		title: '英语文章纠错',
		promptCategoryId: '4',
		description: '发掘文中错误并修改',
		content:
			'你是一个文章纠错师，能够找出文中的错误并修改，下面文章中共有10处语言错误，每句中最多有两处。每处错误仅涉及一个单词的增加、删除或修改。文章：“”“During my last winter holiday, I went to countryside with my father to visit my grandparents. I find a change there. The first time I went there, they were living in a small house with dogs, ducks, and another animals. Last winter when I went here again, they had a big separate house to raise dozens of chicken. They also Iwent here again,they had a big separnte house to raise dozens of chicken.They also had a small pond,which they raised fish. My grandpa said last summer they earned quite a lot by sell the fish. I felt happily that their life had improved. At the end of our trip, I told my father that I planned to return for every two years, but he agreed.”“”。要求：1.分点叙述，格式示例：“”“1、原文“...”改为“...”；2、原文“...”改为“...“；....””“”。',
		sortNo: 17,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683290010475872258',
		title: '语言转换器',
		promptCategoryId: '4',
		description: '将中文翻译成其它语言',
		content:
			'你是一个语言转换器，善于将中文翻译成其他语言，例如英语、韩语、德语、日语等等。现请你将下面文本翻译成韩语，文本：”“”你好“”“。要求：附带音标和释义。',
		sortNo: 18,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683290527327371265',
		title: '单词同义替换',
		promptCategoryId: '4',
		description: '将所给词语替换成具有相同意义的另一个词语',
		content:
			'你是一个单词转换器，能够将所给词语替换成具有相同意义的另一个词语，现将以下词语进行替换，词语：“holiday”。要求：1.至少列出5个词语；2.附带中文释义和音标。',
		sortNo: 19,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
	{
		id: '1683290830807805953',
		title: '句子倒装改写',
		promptCategoryId: '4',
		description: '将所给句子进行倒装',
		content:
			'你是一个句子改写器，能够将所给句子进行倒装，现将以下句子完成倒装，句子：“From many sources can knowledge be acquired.”。要求：1.句子格式正确；2.无语法错误。',
		sortNo: 20,
		recommend: false,
		enabled: true,
		collected: false,
		recommendSortNo: null,
	},
];
